# Generated by Django 4.2.11 on 2024-04-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('color', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, default='Item,Shoe or Hair', max_length=1000, null=True)),
                ('material', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('amount_available', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('dimensions_LHW_in_inches', models.CharField(blank=True, default='0 x 0 x 0', max_length=1000, null=True)),
                ('properties_separated_with_double_comma', models.TextField(blank=True, default='Ankara Item,,Durable', null=True)),
                ('sustainability', models.TextField(blank=True, null=True)),
                ('product_care', models.TextField(blank=True, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('other_images', models.ManyToManyField(blank=True, to='jeniton.images')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Items_Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
                ('counter', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jeniton.items')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('users_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(default='USA', max_length=1000)),
                ('zipcode', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=1000, null=True)),
                ('purchase_id', models.CharField(default=0, max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('apartment', models.CharField(blank=True, max_length=1000, null=True)),
                ('counter', models.IntegerField(default=1)),
                ('success', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('dont_touch_this_for_system_use_only', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ManyToManyField(blank=True, to='jeniton.items_purchases')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
